export function generateTailwindConfig(
  brandName: string,
  palette: { primary: string; secondary: string; background: string; foreground: string }
): string {
  return `/** @type {import("tailwindcss").Config} */
// Generated by KiteBrand for ${brandName}
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: "${palette.primary}",
          secondary: "${palette.secondary}",
          bg: "${palette.background}",
          fg: "${palette.foreground}",
        }
      }
    }
  }
};`;
}
